- name: Setup Docker, Jenkins, and SonarQube on EC2
  hosts: web
  become: true

  tasks:
    ## ---------------- Docker ---------------- ##
    - name: Install prerequisites for Docker
      apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
        state: present
        update_cache: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    ## ---------------- Jenkins ---------------- ##
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Download Jenkins GPG key to trusted store
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repo to sources list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes


    - name: Install Jenkins
      apt:
        name: jenkins
        state: latest
        update_cache: true

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    ## ---------------- SonarQube ---------------- ##
    - name: Install dependencies for SonarQube
      apt:
        name: [unzip, fontconfig, openjdk-17-jdk]
        state: present

    - name: Create sonar user
      user:
        name: sonar
        shell: /bin/bash
        create_home: yes

    - name: Download SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip
        dest: /tmp/sonarqube.zip

    - name: Unzip SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt/
        remote_src: yes

    - name: Rename SonarQube directory
      shell: |
        mv /opt/sonarqube-* /opt/sonarqube
      args:
        creates: /opt/sonarqube

    - name: Set correct permissions
      file:
        path: /opt/sonarqube
        owner: sonar
        group: sonar
        recurse: yes

    - name: Create systemd service for SonarQube
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target

          [Service]
          Type=forking

          ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

          User=sonar
          Group=sonar
          Restart=always
          LimitNOFILE=65536
          LimitNPROC=4096

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reexec

    - name: Enable and start SonarQube
      systemd:
        name: sonarqube
        enabled: yes
        state: started

