name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push bot-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bot-img:latest ./backend/bot-service/
        docker push ${{ secrets.DOCKER_USERNAME }}/bot-img:latest

    - name: Build and push language-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/lang-img:latest ./backend/lang-service
        docker push ${{ secrets.DOCKER_USERNAME }}/lang-img:latest

    - name: Build and push winner-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/database-img:latest ./database
        docker push ${{ secrets.DOCKER_USERNAME }}/database-img:latest

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-img:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-img:latest

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download SonarScanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        mv sonar-scanner-5.0.1.3006-linux sonar-scanner

    - name: Run SonarQube scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./sonar-scanner/bin/sonar-scanner


